### ISSUE TITLE
Please support are: i386 armv7 x86_64 arm64 for simulator.

### ISSUE THREAD

**Issue by wei18** [TapPay/tappay-ios-example#1]
for version 2.3.0

lipo -info tappay-ios-example-2.3.0/Swift/Direct_Pay/TPDirect_Example/TPDirect_Example/TPDirect.framework/Versions/A/TPDirect                             
Architectures in the fat file: tappay-ios-example-2.3.0/Swift/Direct_Pay/TPDirect_Example/TPDirect_Example/TPDirect.framework/Versions/A/TPDirect are: i386 armv7 x86_64 arm64 

for version 2.8.0

lipo -info tappay-ios-example-2.8.0/Swift/Line_Pay/TPDLinePay_Example/TPDLinePay_Example/TPDirect.framework/TPDirect 
Architectures in the fat file: tappay-ios-example-2.8.0/Swift/Line_Pay/TPDLinePay_Example/TPDLinePay_Example/TPDirect.framework/TPDirect are: armv7 arm64

**Comment by TungWang** [comment]
Same problem in v2.8.
Please support.

**Comment by kaojiaqi** [comment]
@TungWang 
您好
方便將您的問題聯絡我們的客服
email:  support@cherri.tech
LINE ID:@712jkrto

**Comment by CharlesChien7996** [comment]
Same problem in version 2.8.0

**Comment by kaojiaqi** [comment]
@CharlesChien7996 
已經更新了 2.8版的 TPDirect.Universal.framework for simulator

如果有其他問題請聯絡我們的客服
email: support@cherri.tech
LINE ID:@712jkrto

謝謝
